[mypy]
python_version = 3.11
strict = true
ignore_missing_imports = true
disallow_untyped_defs = false
disallow_any_unimported = false
disallow_any_expr = false
disallow_any_decorated = false
disallow_any_explicit = false
check_untyped_defs = false
no_implicit_optional = true

[mypy-app.solver.*]
warn_unused_ignores = false

[mypy-app.services.*]
warn_unused_ignores = false
